language: node_js
node_js:
  - '10'
services:
  - docker
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_install:
  - cp .env.testing .env
  - docker-compose up -d
script:
  # Run test script
  - npm run ci
  # Run cypress integration tests
  # - npm run cypress:run
